/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iDverseInterfacesSol from "./IDverse.interfaces.sol";
export * as iDverseSol from "./IDverse.sol";
export { EventLogger__factory } from "./EventLogger__factory";
