/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICredentialRegistry,
  ICredentialRegistryInterface,
} from "../../IDverse.interfaces.sol/ICredentialRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "credentialId",
        type: "bytes32",
      },
    ],
    name: "getCredential",
    outputs: [
      {
        internalType: "address",
        name: "issuer",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "credentialHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "cid",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "issuedAt",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "revoked",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "credentialId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "credentialHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "cid",
        type: "string",
      },
    ],
    name: "issueCredential",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "credentialId",
        type: "bytes32",
      },
    ],
    name: "revokeCredential",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICredentialRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ICredentialRegistryInterface {
    return new Interface(_abi) as ICredentialRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICredentialRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICredentialRegistry;
  }
}
