/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDIDRegistry,
  IDIDRegistryInterface,
} from "../../IDverse.interfaces.sol/IDIDRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "did",
        type: "bytes32",
      },
    ],
    name: "getController",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "did",
        type: "bytes32",
      },
    ],
    name: "getDocPointer",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isController",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "did",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "controllerAddr",
        type: "address",
      },
      {
        internalType: "string",
        name: "pointer",
        type: "string",
      },
    ],
    name: "registerDID",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "did",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "newController",
        type: "address",
      },
    ],
    name: "updateController",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "did",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "pointer",
        type: "string",
      },
    ],
    name: "updateDocPointer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDIDRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IDIDRegistryInterface {
    return new Interface(_abi) as IDIDRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDIDRegistry {
    return new Contract(address, _abi, runner) as unknown as IDIDRegistry;
  }
}
