/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICredentialRegistry__factory } from "./ICredentialRegistry__factory";
export { IDIDRegistry__factory } from "./IDIDRegistry__factory";
