/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "credentials"
      | "getCredential"
      | "issueCredential"
      | "revokeCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialIssued"
      | "CredentialRevoked"
      | "CredentialStatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "credentials",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [BytesLike, AddressLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    credentialId: BytesLike,
    issuer: AddressLike,
    holder: AddressLike,
    credentialHash: BytesLike,
    cid: string
  ];
  export type OutputTuple = [
    credentialId: string,
    issuer: string,
    holder: string,
    credentialHash: string,
    cid: string
  ];
  export interface OutputObject {
    credentialId: string;
    issuer: string;
    holder: string;
    credentialHash: string;
    cid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [credentialId: BytesLike, issuer: AddressLike];
  export type OutputTuple = [credentialId: string, issuer: string];
  export interface OutputObject {
    credentialId: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialStatusUpdatedEvent {
  export type InputTuple = [credentialId: BytesLike, statusPointer: BytesLike];
  export type OutputTuple = [credentialId: string, statusPointer: string];
  export interface OutputObject {
    credentialId: string;
    statusPointer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: CredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  credentials: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean] & {
        issuer: string;
        holder: string;
        credentialHash: string;
        cid: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getCredential: TypedContractMethod<
    [credentialId: BytesLike],
    [
      [string, string, string, string, bigint, boolean] & {
        issuer: string;
        holder: string;
        credentialHash: string;
        cid: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  issueCredential: TypedContractMethod<
    [
      credentialId: BytesLike,
      holder: AddressLike,
      credentialHash: BytesLike,
      cid: string
    ],
    [void],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [credentialId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean] & {
        issuer: string;
        holder: string;
        credentialHash: string;
        cid: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredential"
  ): TypedContractMethod<
    [credentialId: BytesLike],
    [
      [string, string, string, string, bigint, boolean] & {
        issuer: string;
        holder: string;
        credentialHash: string;
        cid: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<
    [
      credentialId: BytesLike,
      holder: AddressLike,
      credentialHash: BytesLike,
      cid: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<[credentialId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialStatusUpdated"
  ): TypedContractEvent<
    CredentialStatusUpdatedEvent.InputTuple,
    CredentialStatusUpdatedEvent.OutputTuple,
    CredentialStatusUpdatedEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(bytes32,address,address,bytes32,string)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,address)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "CredentialStatusUpdated(bytes32,bytes32)": TypedContractEvent<
      CredentialStatusUpdatedEvent.InputTuple,
      CredentialStatusUpdatedEvent.OutputTuple,
      CredentialStatusUpdatedEvent.OutputObject
    >;
    CredentialStatusUpdated: TypedContractEvent<
      CredentialStatusUpdatedEvent.InputTuple,
      CredentialStatusUpdatedEvent.OutputTuple,
      CredentialStatusUpdatedEvent.OutputObject
    >;
  };
}
