/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DIDRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "controller"
      | "docPointer"
      | "getController"
      | "getDocPointer"
      | "registerDID"
      | "updateController"
      | "updateDocPointer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ControllerChanged"
      | "DIDDocUpdated"
      | "DIDRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "controller",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "docPointer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getController",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocPointer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDID",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateController",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDocPointer",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "docPointer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocPointer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDocPointer",
    data: BytesLike
  ): Result;
}

export namespace ControllerChangedEvent {
  export type InputTuple = [
    did: BytesLike,
    previous: AddressLike,
    current: AddressLike
  ];
  export type OutputTuple = [did: string, previous: string, current: string];
  export interface OutputObject {
    did: string;
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDDocUpdatedEvent {
  export type InputTuple = [did: BytesLike, newDocPointer: string];
  export type OutputTuple = [did: string, newDocPointer: string];
  export interface OutputObject {
    did: string;
    newDocPointer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDRegisteredEvent {
  export type InputTuple = [
    did: BytesLike,
    controller: AddressLike,
    docPointer: string
  ];
  export type OutputTuple = [
    did: string,
    controller: string,
    docPointer: string
  ];
  export interface OutputObject {
    did: string;
    controller: string;
    docPointer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DIDRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DIDRegistry;
  waitForDeployment(): Promise<this>;

  interface: DIDRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  controller: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  docPointer: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getController: TypedContractMethod<[did: BytesLike], [string], "view">;

  getDocPointer: TypedContractMethod<[did: BytesLike], [string], "view">;

  registerDID: TypedContractMethod<
    [did: BytesLike, controllerAddr: AddressLike, pointer: string],
    [void],
    "nonpayable"
  >;

  updateController: TypedContractMethod<
    [did: BytesLike, newController: AddressLike],
    [void],
    "nonpayable"
  >;

  updateDocPointer: TypedContractMethod<
    [did: BytesLike, pointer: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "controller"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "docPointer"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getController"
  ): TypedContractMethod<[did: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDocPointer"
  ): TypedContractMethod<[did: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerDID"
  ): TypedContractMethod<
    [did: BytesLike, controllerAddr: AddressLike, pointer: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateController"
  ): TypedContractMethod<
    [did: BytesLike, newController: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateDocPointer"
  ): TypedContractMethod<
    [did: BytesLike, pointer: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ControllerChanged"
  ): TypedContractEvent<
    ControllerChangedEvent.InputTuple,
    ControllerChangedEvent.OutputTuple,
    ControllerChangedEvent.OutputObject
  >;
  getEvent(
    key: "DIDDocUpdated"
  ): TypedContractEvent<
    DIDDocUpdatedEvent.InputTuple,
    DIDDocUpdatedEvent.OutputTuple,
    DIDDocUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DIDRegistered"
  ): TypedContractEvent<
    DIDRegisteredEvent.InputTuple,
    DIDRegisteredEvent.OutputTuple,
    DIDRegisteredEvent.OutputObject
  >;

  filters: {
    "ControllerChanged(bytes32,address,address)": TypedContractEvent<
      ControllerChangedEvent.InputTuple,
      ControllerChangedEvent.OutputTuple,
      ControllerChangedEvent.OutputObject
    >;
    ControllerChanged: TypedContractEvent<
      ControllerChangedEvent.InputTuple,
      ControllerChangedEvent.OutputTuple,
      ControllerChangedEvent.OutputObject
    >;

    "DIDDocUpdated(bytes32,string)": TypedContractEvent<
      DIDDocUpdatedEvent.InputTuple,
      DIDDocUpdatedEvent.OutputTuple,
      DIDDocUpdatedEvent.OutputObject
    >;
    DIDDocUpdated: TypedContractEvent<
      DIDDocUpdatedEvent.InputTuple,
      DIDDocUpdatedEvent.OutputTuple,
      DIDDocUpdatedEvent.OutputObject
    >;

    "DIDRegistered(bytes32,address,string)": TypedContractEvent<
      DIDRegisteredEvent.InputTuple,
      DIDRegisteredEvent.OutputTuple,
      DIDRegisteredEvent.OutputObject
    >;
    DIDRegistered: TypedContractEvent<
      DIDRegisteredEvent.InputTuple,
      DIDRegisteredEvent.OutputTuple,
      DIDRegisteredEvent.OutputObject
    >;
  };
}
