/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IDIDRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getController"
      | "getDocPointer"
      | "registerDID"
      | "updateController"
      | "updateDocPointer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getController",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocPointer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDID",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateController",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDocPointer",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocPointer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDocPointer",
    data: BytesLike
  ): Result;
}

export interface IDIDRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IDIDRegistry;
  waitForDeployment(): Promise<this>;

  interface: IDIDRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getController: TypedContractMethod<[did: BytesLike], [string], "view">;

  getDocPointer: TypedContractMethod<[did: BytesLike], [string], "view">;

  registerDID: TypedContractMethod<
    [did: BytesLike, controllerAddr: AddressLike, pointer: string],
    [void],
    "nonpayable"
  >;

  updateController: TypedContractMethod<
    [did: BytesLike, newController: AddressLike],
    [void],
    "nonpayable"
  >;

  updateDocPointer: TypedContractMethod<
    [did: BytesLike, pointer: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getController"
  ): TypedContractMethod<[did: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDocPointer"
  ): TypedContractMethod<[did: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerDID"
  ): TypedContractMethod<
    [did: BytesLike, controllerAddr: AddressLike, pointer: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateController"
  ): TypedContractMethod<
    [did: BytesLike, newController: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateDocPointer"
  ): TypedContractMethod<
    [did: BytesLike, pointer: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
