/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICredentialRegistry } from "./ICredentialRegistry";
export type { IDIDRegistry } from "./IDIDRegistry";
