/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EventLoggerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accessLogs"
      | "addAuthorizedVerifier"
      | "authorizedVerifiers"
      | "getAccessLog"
      | "getAccessLogCount"
      | "getVerificationCount"
      | "getVerificationHistory"
      | "isAuthorizedVerifier"
      | "logAccess"
      | "logVerification"
      | "owner"
      | "removeAuthorizedVerifier"
      | "transferOwnership"
      | "verificationHistory"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessAttempt"
      | "CredentialVerified"
      | "VerifierAuthorized"
      | "VerifierDeauthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accessLogs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addAuthorizedVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedVerifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessLog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessLogCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logAccess",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "logVerification",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationHistory",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "accessLogs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addAuthorizedVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessLogCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "logVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationHistory",
    data: BytesLike
  ): Result;
}

export namespace AccessAttemptEvent {
  export type InputTuple = [
    credentialId: BytesLike,
    accessor: AddressLike,
    timestamp: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [
    credentialId: string,
    accessor: string,
    timestamp: bigint,
    success: boolean
  ];
  export interface OutputObject {
    credentialId: string;
    accessor: string;
    timestamp: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialVerifiedEvent {
  export type InputTuple = [
    credentialId: BytesLike,
    verifier: AddressLike,
    timestamp: BigNumberish,
    result: boolean
  ];
  export type OutputTuple = [
    credentialId: string,
    verifier: string,
    timestamp: bigint,
    result: boolean
  ];
  export interface OutputObject {
    credentialId: string;
    verifier: string;
    timestamp: bigint;
    result: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierAuthorizedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierDeauthorizedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventLogger extends BaseContract {
  connect(runner?: ContractRunner | null): EventLogger;
  waitForDeployment(): Promise<this>;

  interface: EventLoggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accessLogs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        accessor: string;
        credentialId: string;
        timestamp: bigint;
        success: boolean;
      }
    ],
    "view"
  >;

  addAuthorizedVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedVerifiers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getAccessLog: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        accessor: string;
        credentialId: string;
        timestamp: bigint;
        success: boolean;
      }
    ],
    "view"
  >;

  getAccessLogCount: TypedContractMethod<[], [bigint], "view">;

  getVerificationCount: TypedContractMethod<
    [credentialId: BytesLike],
    [bigint],
    "view"
  >;

  getVerificationHistory: TypedContractMethod<
    [credentialId: BytesLike],
    [bigint[]],
    "view"
  >;

  isAuthorizedVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [boolean],
    "view"
  >;

  logAccess: TypedContractMethod<
    [credentialId: BytesLike, success: boolean],
    [void],
    "nonpayable"
  >;

  logVerification: TypedContractMethod<
    [credentialId: BytesLike, result: boolean],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeAuthorizedVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verificationHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accessLogs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        accessor: string;
        credentialId: string;
        timestamp: bigint;
        success: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "addAuthorizedVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedVerifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAccessLog"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        accessor: string;
        credentialId: string;
        timestamp: bigint;
        success: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccessLogCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVerificationCount"
  ): TypedContractMethod<[credentialId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVerificationHistory"
  ): TypedContractMethod<[credentialId: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "logAccess"
  ): TypedContractMethod<
    [credentialId: BytesLike, success: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logVerification"
  ): TypedContractMethod<
    [credentialId: BytesLike, result: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAuthorizedVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificationHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "AccessAttempt"
  ): TypedContractEvent<
    AccessAttemptEvent.InputTuple,
    AccessAttemptEvent.OutputTuple,
    AccessAttemptEvent.OutputObject
  >;
  getEvent(
    key: "CredentialVerified"
  ): TypedContractEvent<
    CredentialVerifiedEvent.InputTuple,
    CredentialVerifiedEvent.OutputTuple,
    CredentialVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierAuthorized"
  ): TypedContractEvent<
    VerifierAuthorizedEvent.InputTuple,
    VerifierAuthorizedEvent.OutputTuple,
    VerifierAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierDeauthorized"
  ): TypedContractEvent<
    VerifierDeauthorizedEvent.InputTuple,
    VerifierDeauthorizedEvent.OutputTuple,
    VerifierDeauthorizedEvent.OutputObject
  >;

  filters: {
    "AccessAttempt(bytes32,address,uint256,bool)": TypedContractEvent<
      AccessAttemptEvent.InputTuple,
      AccessAttemptEvent.OutputTuple,
      AccessAttemptEvent.OutputObject
    >;
    AccessAttempt: TypedContractEvent<
      AccessAttemptEvent.InputTuple,
      AccessAttemptEvent.OutputTuple,
      AccessAttemptEvent.OutputObject
    >;

    "CredentialVerified(bytes32,address,uint256,bool)": TypedContractEvent<
      CredentialVerifiedEvent.InputTuple,
      CredentialVerifiedEvent.OutputTuple,
      CredentialVerifiedEvent.OutputObject
    >;
    CredentialVerified: TypedContractEvent<
      CredentialVerifiedEvent.InputTuple,
      CredentialVerifiedEvent.OutputTuple,
      CredentialVerifiedEvent.OutputObject
    >;

    "VerifierAuthorized(address)": TypedContractEvent<
      VerifierAuthorizedEvent.InputTuple,
      VerifierAuthorizedEvent.OutputTuple,
      VerifierAuthorizedEvent.OutputObject
    >;
    VerifierAuthorized: TypedContractEvent<
      VerifierAuthorizedEvent.InputTuple,
      VerifierAuthorizedEvent.OutputTuple,
      VerifierAuthorizedEvent.OutputObject
    >;

    "VerifierDeauthorized(address)": TypedContractEvent<
      VerifierDeauthorizedEvent.InputTuple,
      VerifierDeauthorizedEvent.OutputTuple,
      VerifierDeauthorizedEvent.OutputObject
    >;
    VerifierDeauthorized: TypedContractEvent<
      VerifierDeauthorizedEvent.InputTuple,
      VerifierDeauthorizedEvent.OutputTuple,
      VerifierDeauthorizedEvent.OutputObject
    >;
  };
}
