/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "EventLogger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EventLogger__factory>;
    getContractFactory(
      name: "ICredentialRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICredentialRegistry__factory>;
    getContractFactory(
      name: "IDIDRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDIDRegistry__factory>;
    getContractFactory(
      name: "CredentialRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CredentialRegistry__factory>;
    getContractFactory(
      name: "DIDRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DIDRegistry__factory>;

    getContractAt(
      name: "EventLogger",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EventLogger>;
    getContractAt(
      name: "ICredentialRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICredentialRegistry>;
    getContractAt(
      name: "IDIDRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDIDRegistry>;
    getContractAt(
      name: "CredentialRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CredentialRegistry>;
    getContractAt(
      name: "DIDRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DIDRegistry>;

    deployContract(
      name: "EventLogger",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EventLogger>;
    deployContract(
      name: "ICredentialRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICredentialRegistry>;
    deployContract(
      name: "IDIDRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDIDRegistry>;
    deployContract(
      name: "CredentialRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CredentialRegistry>;
    deployContract(
      name: "DIDRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DIDRegistry>;

    deployContract(
      name: "EventLogger",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EventLogger>;
    deployContract(
      name: "ICredentialRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICredentialRegistry>;
    deployContract(
      name: "IDIDRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDIDRegistry>;
    deployContract(
      name: "CredentialRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CredentialRegistry>;
    deployContract(
      name: "DIDRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DIDRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
