/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iDverseInterfacesSol from "./IDverse.interfaces.sol";
export type { iDverseInterfacesSol };
import type * as iDverseSol from "./IDverse.sol";
export type { iDverseSol };
export type { EventLogger } from "./EventLogger";
export * as factories from "./factories";
export { EventLogger__factory } from "./factories/EventLogger__factory";
export type { ICredentialRegistry } from "./IDverse.interfaces.sol/ICredentialRegistry";
export { ICredentialRegistry__factory } from "./factories/IDverse.interfaces.sol/ICredentialRegistry__factory";
export type { IDIDRegistry } from "./IDverse.interfaces.sol/IDIDRegistry";
export { IDIDRegistry__factory } from "./factories/IDverse.interfaces.sol/IDIDRegistry__factory";
export type { CredentialRegistry } from "./IDverse.sol/CredentialRegistry";
export { CredentialRegistry__factory } from "./factories/IDverse.sol/CredentialRegistry__factory";
export type { DIDRegistry } from "./IDverse.sol/DIDRegistry";
export { DIDRegistry__factory } from "./factories/IDverse.sol/DIDRegistry__factory";
